 server:
  port: 8081

 spring:
  application:
    name: book-service
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   
  datasource:
    url: jdbc:mysql://localhost/book-service
    username: admin
    password: admin

  flyway:
    enabled: true
